<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:ivy="antlib:org.apache.ivy.ant" basedir="." default="publish">
	
	<property name="build" value="build"/>
	<ivy:settings file="../ivy_settings/ivysettings.xml" />
	
	<target name="clean">
		<delete dir="${build}"/>
		<delete dir="lib"/>
	</target>
	
	<target name="init" depends="clean">
		<mkdir dir="${build}"/>
	</target>
	
	<target name="resolve" description="--> retrieve dependencies with ivy" depends="init">
		<ivy:retrieve />
		<ivy:cachepath pathid="default.classpath" />
	</target>
	
	<target name="compile" depends="resolve">
		<!-- Compile the java code -->
		<javac srcdir="src" destdir="${build}" debug="true" debuglevel="lines,vars,source">
			<classpath refid="default.classpath" />
		</javac>
	</target>
	
  	<target name="jar" depends="compile">
		<!-- Build the jar file -->
		<jar basedir="${build}" destfile="${build}/utils.jar">
			<fileset dir="src" includes="**/*.java"/>
		</jar>
	</target>
  	
	<target name="publish" depends="jar">
        <ivy:publish resolver="ivysvn" pubrevision="1.21" update="true" overwrite="true">
        	<artifacts pattern="${build}/[artifact].[ext]"/>
        </ivy:publish>
		<delete dir="${build}"/>
		<delete dir="lib"/>
	</target>
</project>